const translations = {
	en: {
		t1: "Scan your device",
		t2: "Scanned",
		t3: "Files",
		t4: "Results summary",
		t5: "Total items scanned:",
		t6: "Total security risks detected:",
		t7: "Total vulnerabilities resolved:",
		t8: "Total security risks requiring attention:",
		t9: "Your computer is infected with viruses. Cleaning is highly recommended.",
		t10: "Start cleaning",
		t11: "Threat detected!",
		t12: "High risk",
		t13: "Origin",
		t14: "Not available",
		t15: "Activity",
		t16: "Threat actions taken: 1",
		t17: "Medium risk",
	},
	de: {
		t1: "Scannen Ihres Geräts",
		t2: "Gescannt",
		t3: "Dateien",
		t4: "Zusammenfassung der Ergebnisse",
		t5: "Gesamtzahl der gescannten Elemente:",
		t6: "Insgesamt erkannte Sicherheitsrisiken:",
		t7: "Insgesamt behobene Sicherheitsrisiken:",
		t8: "Gesamtzahl der Sicherheitsrisiken, die beachtet werden müssen:",
		t9: "Ihr Computer ist mit Viren infiziert. Eine Bereinigung wird dringend empfohlen.",
		t10: "Bereinigung starten",
		t11: "Bedrohung erkannt!",
		t12: "Hohes Risiko",
		t13: "Herkunft",
		t14: "Nicht verfügbar",
		t15: "Aktivität",
		t16: "Durchgeführte Bedrohungsaktionen: 1",
		t17: "Mittleres Risiko",
	},
	fr: {
		t1: "Analyser votre appareil",
		t2: "Scanné",
		t3: "Fichiers",
		t4: "Résumé des résultats",
		t5: "Nombre total d'éléments analysés :",
		t6: "Total des risques de sécurité détectés :",
		t7: "Total des vulnérabilités résolues :",
		t8: "Nombre total de risques de sécurité nécessitant une attention particulière :",
		t9: "Votre ordinateur est infecté par des virus. Un nettoyage est fortement recommandé.",
		t10: "Démarrer le nettoyage",
		t11: "Menace détectée !",
		t12: "Risque élevé",
		t13: "Origine",
		t14: "Non disponible",
		t15: "Activité",
		t16: "Actions de menace prises : 1",
		t17: "Risque moyen",
	},
	es: {
		t1: "Analice su dispositivo",
		t2: "Analizaron",
		t3: "Archivos",
		t4: "Resumen de resultados",
		t5: "Total de elementos analizados:",
		t6: "Total de riesgos de seguridad detectados:",
		t7: "Total de vulnerabilidades resueltas:",
		t8: "Total de riesgos de seguridad que requieren atención:",
		t9: "Su computadora está infectada con virus. Se recomienda encarecidamente la limpieza",
		t10: "Iniciar limpieza",
		t11: "¡Amenaza detectada!",
		t12: "Riesgo alto",
		t13: "Origen",
		t14: "No disponible",
		t15: "Actividad",
		t16: "Acciones de amenaza tomadas: 1",
		t17: "Riesgo medio",
	},
	tr: {
		t1: "Cihazınızı tarayın",
		t2: "Tarandı",
		t3: "Dosyalar",
		t4: "Sonuç özeti",
		t5: "Taranan toplam öğe:",
		t6: "Algılanan toplam güvenlik riski:",
		t7: "Çözülen toplam güvenlik açığı:",
		t8: "Dikkat gerektiren toplam güvenlik riski:",
		t9: "Bilgisayarınız virüslerle enfekte. Temizleme şiddetle önerilir.",
		t10: "Temizlemeye başla",
		t11: "Tehdit algılandı!",
		t12: "Yüksek risk",
		t13: "Köken",
		t14: "Kullanılamaz",
		t15: "Etkinlik",
		t16: "Alınan tehdit eylemleri: 1",
		t17: "Orta risk",
	},
	gr: {
		t1: "Σάρωση της συσκευής σας",
		t2: "Σάρωση",
		t3: "Αρχεία",
		t4: "Σύνοψη αποτελεσμάτων",
		t5: "Σύνολο στοιχείων που σαρώθηκαν:",
		t6: "Εντοπίστηκαν συνολικοί κίνδυνοι ασφάλειας:",
		t7: "Επιλύθηκαν συνολικές ευπάθειες:",
		t8: "Συνολικοί κίνδυνοι ασφάλειας που απαιτούν προσοχή:",
		t9: "Ο υπολογιστής σας έχει μολυνθεί από ιούς. Συνιστάται ιδιαίτερα ο καθαρισμός.",
		t10: "Έναρξη καθαρισμού",
		t11: "Εντοπίστηκε απειλή!",
		t12: "Υψηλού κινδύνου",
		t13: "Προέλευση",
		t14: "Μη διαθέσιμο",
		t15: "Δραστηριότητα",
		t16: "Ενέργειες απειλών που έγιναν: 1",
		t17: "Μεσαίος κίνδυνος",
	},
	my: {
		t1: "Imbas peranti anda",
		t2: "Diimbas",
		t3: "Fail",
		t4: "Ringkasan keputusan",
		t5: "Jumlah item yang diimbas:",
		t6: "Jumlah risiko keselamatan dikesan:",
		t7: "Jumlah kelemahan diselesaikan:",
		t8: "Jumlah risiko keselamatan yang memerlukan perhatian:",
		t9: "Komputer anda dijangkiti virus. Pembersihan amat disyorkan.",
		t10: "Mulakan pembersihan",
		t11: "Ancaman dikesan!",
		t12: "Risiko tinggi",
		t13: "Asal usul",
		t14: "Tidak tersedia",
		t15: "Aktiviti",
		t16: "Tindakan ancaman yang diambil: 1",
		t17: "Risiko sederhana",
	},
	jp: {
		t1: "デバイスをスキャン",
		t2: "スキャン済み",
		t3: "ファイル",
		t4: "結果の概要",
		t5: "スキャンされたアイテムの合計数:",
		t6: "検出されたセキュリティ リスクの合計数:",
		t7: "解決された脆弱性の合計数:",
		t8: "注意が必要なセキュリティ リスクの合計数:",
		t9: "コンピュータがウイルスに感染しています。クリーニングを強くお勧めします。",
		t10: "クリーニングを開始",
		t11: "脅威が検出されました!",
		t12: "高リスク",
		t13: "発信元",
		t14: "利用不可",
		t15: "アクティビティ",
		t16: "実行された脅威アクション: 1",
		t17: "中リスク",
	},
	il: {
		t1: "סרוק את המכשיר שלך",
		t2: "נסרק",
		t3: "קבצים",
		t4: "סיכום תוצאות",
		t5: "סך כל הפריטים שנסרקו:",
		t6: "סיכוני אבטחה הכוללים זוהו:",
		t7: "סך הכל פגיעויות נפתרו:",
		t8: "סיכוני אבטחה מוחלטים הדורשים תשומת לב:",
		t9: "המחשב שלך נגוע בווירוסים. ניקוי מומלץ מאוד.",
		t10: "התחל לנקות",
		t11: "זוהה איום!",
		t12: "סיכון גבוה",
		t13: "מקור",
		t14: "לא זמין",
		t15: "פעילות",
		t16: "פעולות איום שננקטו: 1",
		t17: "סיכון בינוני",
	},
	ro: {
		t1: "Scanează-ți dispozitivul",
		t2: "Scanat",
		t3: "Fișiere",
		t4: "Rezumatul rezultatelor",
		t5: "Total articole scanate:",
		t6: "Riscuri totale de securitate detectate:",
		t7: "Vulnerabilități totale rezolvate:",
		t8: "Riscuri totale de securitate care necesită atenție:",
		t9: "Computerul dumneavoastră este infectat cu viruși. Curățarea este foarte recomandată.",
		t10: "Începe curățarea",
		t11: "Amenințare detectată!",
		t12: "Risc ridicat",
		t13: "Origine",
		t14: "Nu este disponibil",
		t15: "Activitate",
		t16: "Acțiuni de amenințare întreprinse: 1",
		t17: "Risc mediu",
	},
	it: {
		t1: "Scansiona il tuo dispositivo",
		t2: "Scansionato",
		t3: "File",
		t4: "Riepilogo dei risultati",
		t5: "Totale elementi scansionati:",
		t6: "Totale rischi per la sicurezza rilevati:",
		t7: "Totale vulnerabilità risolte:",
		t8: "Totale rischi per la sicurezza che richiedono attenzione:",
		t9: "Il tuo computer è infetto da virus. Si consiglia vivamente di pulirlo.",
		t10: "Avvia pulirlo",
		t11: "Minaccia rilevata!",
		t12: "Rischio elevato",
		t13: "Origine",
		t14: "Non disponibile",
		t15: "Attività",
		t16: "Azioni di minaccia intraprese: 1",
		t17: "Rischio medio",
	},
	dk: {
		t1: "Scan din enhed",
		t2: "Scannet",
		t3: "Filer",
		t4: "Resultatoversigt",
		t5: "I alt scannede varer:",
		t6: "Totale sikkerhedsrisici opdaget:",
		t7: "Totale sårbarheder løst:",
		t8: "Totale sikkerhedsrisici kræver opmærksomhed:",
		t9: "Din computer er inficeret med virus. Rengøring anbefales stærkt.",
		t10: "Start rengøring",
		t11: "Trussel opdaget!",
		t12: "Høj risiko",
		t13: "Oprindelse",
		t14: "Ikke tilgængelig",
		t15: "Aktivitet",
		t16: "Truede handlinger: 1",
		t17: "Middel risiko",
	},
	no: {
		t1: "Skann enheten din",
		t2: "Skannet",
		t3: "Filer",
		t4: "Resultatsammendrag",
		t5: "Totalt skannete varer:",
		t6: "Total sikkerhetsrisiko oppdaget:",
		t7: "Totale sårbarheter løst:",
		t8: "Totale sikkerhetsrisikoer som krever oppmerksomhet:",
		t9: "Datamaskinen din er infisert med virus. Rengjøring anbefales på det sterkeste.",
		t10: "Start rengjøring",
		t11: "Trussel oppdaget!",
		t12: "Høy risiko",
		t13: "Opprinnelse",
		t14: "Ikke tilgjengelig",
		t15: "Aktivitet",
		t16: "Trusselhandlinger utført: 1",
		t17: "Middels risiko",
	},
	se: {
		t1: "Skanna din enhet",
		t2: "Scanned",
		t3: "Filer",
		t4: "Resultatsammanfattning",
		t5: "Totalt antal skannade objekt:",
		t6: "Totala säkerhetsrisker upptäckt:",
		t7: "Totala sårbarheter lösta:",
		t8: "Totala säkerhetsrisker som kräver uppmärksamhet:",
		t9: "Din dator är infekterad med virus. Rengöring rekommenderas starkt.",
		t10: "Börja städa",
		t11: "Hot upptäckt!",
		t12: "Hög risk",
		t13: "Ursprung",
		t14: "Inte tillgängligt",
		t15: "Aktivitet",
		t16: "Hotåtgärder vidtagna: 1",
		t17: "Medellång risk",
	},
	pt: {
		t1: "Verifique o seu dispositivo",
		t2: "Escaneado",
		t3: "Arquivos",
		t4: "Resumo dos resultados",
		t5: "Total de itens verificados:",
		t6: "Total de riscos de segurança detetados:",
		t7: "Total de vulnerabilidades resolvidas:",
		t8: "Riscos totais de segurança que requerem atenção:",
		t9: "O seu computador está infetado com vírus. A limpeza é altamente recomendada.",
		t10: "Iniciar limpeza",
		t11: "Ameaça detectada!",
		t12: "Alto risco",
		t13: "Origem",
		t14: "Não disponível",
		t15: "Atividade",
		t16: "Ações de ameaça tomadas: 1",
		t17: "Risco médio",
	},
}

function setLanguage(lang) {
	const elements = document.querySelectorAll('[data-trans]');
	elements.forEach(element => {
		const key = element.getAttribute('data-trans');
		if (translations[lang] && translations[lang][key]) {
			element.innerHTML = translations[lang][key];
		}
	})

}

let lang = getOneParam('lang')
if (lang) {
	setLanguage(lang)
}